name: Release Changelog to Discord

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      changelog:
        description: "Release notes"
        required: false

env:
    CHANGELOG: ${{ github.event.inputs.changelog }}
jobs:
  notify-discord:
    if: github.event.release.target_commitish == 'main-2'
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Send release info to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')
        echo $PREVIOUS_TAG

        CURRENT_TAG=${{ github.event.release.tag_name }}
        echo $CURRENT_TAG

        CHANGELOG=$(git log --no-merges --pretty=format:"- %s" $PREVIOUS_TAG..$CURRENT_TAG)
        echo $CHANGELOG

        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="- No changes detected"
        fi

        {
          echo "CHANGELOG<<EOF"
          echo "$CHANGELOG"
          echo "EOF"
        } >> $GITHUB_ENV

    - name: Discord Commits
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      with:
        args: "deployment done - Check it out: ${{ env.CHANGELOG != '' && format('Release notes: ```\n{0}```', env.CHANGELOG) || '' }}"
