name: Release Changelog to Discord

on:
  release:
    types: [published]

jobs:
  notify-discord:
    if: github.event.release.target_commitish == 'main-2'
    runs-on: ubuntu-latest

    steps:
    - name: Send release info to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')
        CURRENT_TAG=${{ github.event.release.tag_name }}
        CHANGELOG=$(git log --no-merges --pretty=format:"- %s" $PREVIOUS_TAG..CURRENT_TAG)

        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="- No changes detected"